In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# 7.2 Self Check #2

In [7]:
import numpy as np

In [8]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
# 7.2 Self Check #3

In [10]:
import numpy as np

In [11]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [12]:
#7.3 Practice

In [13]:
import numpy as np

In [14]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [17]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [18]:
integers.dtype

dtype('int32')

In [19]:
floats.dtype

dtype('float64')

In [20]:
integers.ndim

2

In [21]:
floats.ndim

1

In [22]:
integers.shape

(2, 3)

In [23]:
floats.shape

(5,)

In [24]:
integers.size

6

In [25]:
integers.itemsize

4

In [26]:
floats.size

5

In [27]:
floats.itemsize

8

In [28]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [29]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

In [30]:
#Self Check 7.3 # 2

In [31]:
import numpy as np

In [32]:
a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [33]:
a.ndim

2

In [34]:
a.shape

(2, 5)

In [35]:
#7.4 Practice

In [36]:
import numpy as np

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [40]:
#7.5 Practice

In [41]:
import numpy as np

In [42]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [44]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [45]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
np.linspace(0.0, 1.0)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [47]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [49]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [50]:
#Self Check 7.5 2

In [51]:
import numpy as np

In [52]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [53]:
#7.6 Practice

In [54]:
import random

In [55]:
%timeit rolls_list = \
    [random.randrange(1, 7) for i in range(0, 6_000_000)]

4.58 s ± 149 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
import numpy as np

In [57]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

62 ms ± 2.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [58]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

625 ms ± 29.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

6.28 s ± 114 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [60]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

66.5 ms ± 1.93 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [61]:
# Self Check 7.6

In [62]:
import numpy as np

In [63]:
%timeit sum([x for x in range(10_000_000)])

876 ms ± 49.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [64]:
%timeit  np.arange(10_000_000).sum()

18.3 ms ± 1.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
#7.7 Practice

In [66]:
import numpy as np

In [67]:
numbers = np.arange(1, 6)

In [68]:
numbers

array([1, 2, 3, 4, 5])

In [69]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [70]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [71]:
numbers

array([1, 2, 3, 4, 5])

In [72]:
numbers += 10

In [73]:
numbers

array([11, 12, 13, 14, 15])

In [74]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [75]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [76]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [77]:
numbers

array([11, 12, 13, 14, 15])

In [78]:
numbers >= 13

array([False, False,  True,  True,  True])

In [79]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [80]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [81]:
numbers == numbers2

array([False, False, False, False, False])

In [82]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [83]:
#Self Check 7.7

In [84]:
import numpy as np

In [85]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])

In [86]:
# 7.8 Practice

In [87]:
import numpy as np

In [88]:
grades = np.array([[87, 96, 70], [100, 87, 90], 
                   [94, 77, 90], [100, 81, 82]])

In [89]:
grades.sum()

1054

In [90]:
grades.min()

70

In [91]:
grades.max()

100

In [92]:
grades.mean()

87.83333333333333

In [93]:
grades.std()

8.792357792739987

In [94]:
grades.var()

77.30555555555556

In [95]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [96]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [97]:
#Self Check 7.8

In [98]:
import numpy as np

In [99]:
grades = np.random.randint(60, 100, 12).reshape(3, 4)

In [100]:
grades

array([[79, 81, 63, 86],
       [60, 78, 66, 75],
       [95, 77, 94, 74]])

In [101]:
grades.mean()

77.33333333333333

In [102]:
grades.mean(axis=0)

array([78.        , 78.66666667, 74.33333333, 78.33333333])

In [103]:
grades.mean(axis=1)

array([77.25, 69.75, 85.  ])

In [104]:
#7.9 Practice

In [105]:
import numpy as np

In [106]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [107]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [108]:
numbers2 = np.arange(1, 7) * 10

In [109]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [110]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [111]:
np.multiply(numbers2,5)

array([ 50, 100, 150, 200, 250, 300])

In [112]:
numbers3 = numbers2.reshape(2, 3)

In [113]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [114]:
numbers4 = np.array([2, 4, 6])

In [115]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [116]:
#Self Check 7.9

In [117]:
import numpy as np

In [118]:
numbers = np.arange(1, 6)

In [119]:
np.power(numbers, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [120]:
#7.10 Practice

In [121]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [122]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [123]:
grades[0, 1]

96

In [124]:
grades[1]

array([100,  87,  90])

In [125]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [126]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [127]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [128]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [129]:
# Self Check 7.10

In [130]:
import numpy as np

In [131]:
a = np.arange(1, 16).reshape(3, 5)

In [132]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [133]:
a[1]

array([ 6,  7,  8,  9, 10])

In [134]:
a[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [135]:
a[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [136]:
# 7.11 Practice

In [137]:
import numpy as np

In [138]:
numbers = np.arange(1, 6)

In [139]:
numbers

array([1, 2, 3, 4, 5])

In [140]:
numbers2 = numbers.view()

In [141]:
numbers2

array([1, 2, 3, 4, 5])

In [142]:
id(numbers)

1179757475376

In [143]:
id(numbers2)

1179757994128

In [144]:
numbers[1] *= 10

In [145]:
numbers2

array([ 1, 20,  3,  4,  5])

In [146]:
numbers

array([ 1, 20,  3,  4,  5])

In [147]:
numbers2[1] /= 10

In [148]:
numbers

array([1, 2, 3, 4, 5])

In [149]:
numbers2

array([1, 2, 3, 4, 5])

In [150]:
numbers2 = numbers[0:3]

In [151]:
numbers2

array([1, 2, 3])

In [152]:
id(numbers)

1179757475376

In [153]:
id(numbers2)

1179757918992

In [154]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [155]:
numbers[1] *= 20

In [156]:
numbers

array([ 1, 40,  3,  4,  5])

In [157]:
numbers2

array([ 1, 40,  3])

In [158]:
# 7.12 Practice

In [159]:
import numpy as np

In [160]:
numbers = np.arange(1, 6)

In [161]:
numbers

array([1, 2, 3, 4, 5])

In [162]:
numbers2 = numbers.copy()

In [163]:
numbers2

array([1, 2, 3, 4, 5])

In [164]:
numbers[1] *= 10

In [165]:
numbers

array([ 1, 20,  3,  4,  5])

In [166]:
numbers2

array([1, 2, 3, 4, 5])

In [167]:
# 7.13 Practice

In [168]:
import numpy as np

In [169]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [170]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [171]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [172]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [173]:
grades.resize(1, 6)

In [174]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [175]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [176]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [177]:
flattened = grades.flatten()

In [178]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [179]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [180]:
flattened[0] = 100

In [181]:
flattened

array([100,  96,  70, 100,  87,  90])

In [182]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [183]:
raveled = grades.ravel()

In [184]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [185]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [186]:
raveled[0] = 100

In [187]:
raveled

array([100,  96,  70, 100,  87,  90])

In [188]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [189]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [190]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [191]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [192]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [193]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [194]:
# Self Check 7.13

In [195]:
import numpy as np

In [196]:
a = np.arange(1, 7).reshape(2, 3)

In [197]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [198]:
a = np.hstack((a, a))

In [199]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [200]:
a = np.vstack((a, a))

In [201]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [202]:
# 7.14 Self Check

In [203]:
import numpy as np

In [204]:
import pandas as pd

In [205]:
temps = np.random.randint(60, 101, 5)

In [206]:
temperatures = pd.Series(temps)

In [207]:
temperatures

0    72
1    77
2    84
3    96
4    65
dtype: int32

In [208]:
temperatures.min()

65

In [209]:
temperatures.max()

96

In [210]:
temperatures.mean()

78.8

temperatures.describe()

In [211]:
#Self Check 7.14

In [212]:
import pandas as pd

In [213]:
temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82], 'Thu': [75, 97], 'Fri': [62, 79]}

In [214]:
temperatures = pd.DataFrame(temps, index=['Low', 'High'])

In [215]:
temperatures

Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79

In [216]:
temperatures.loc[:, 'Mon':'Wed']

Mon  Tue  Wed
Low    68   71   66
High   89   93   82

In [217]:
temperatures.loc['Low']

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64

In [218]:
pd.set_option('precision', 2)

In [219]:
temperatures.mean()

Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64

In [220]:
temperatures.mean(axis=1)

Low     68.4
High    88.0
dtype: float64